#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: sandwich
# @Date:   2018-09-23 22:48:44
# @Last Modified by:   sandwich
# @Last Modified time: 2018-09-23 23:17:34

"""
queue先进先出
线程内安全，收集的位置却未定哦
"""
import threading
import time
from queue import Queue

def job(l, q):	#将队列作为参数传递
	for i in range(len(l)):
		print(threading.current_thread(),'正在计算')
		l[i] = l[i] ** 2
	q.put(l)	#结果用队列收集
	print(threading.current_thread(),'结束')

def multithreading(data):
	length = len(data)
	q = Queue()
	threads = []
	for  i in range(length):
		t = threading.Thread(target=job, args=(data[i], q), name='T%s' % i)
		t.start()
		threads.append(t)
	for t in threads:
		t.join()
	result = []
	for _ in range(length):
		result.append(q.get())
	print(result)


if __name__ == '__main__':
	data = [[1,2,4], [2,6,7, 1, 2, 3, 2, 2, 4, 34,45,56,34,345,3545,34,23,23,12,1212,1222,111], [2,5,3]]
	multithreading(data)
	
